name: Update API specs 
on:
  repository_dispatch:
    types: openapi-spec-change
  schedule:
    - cron: '0 0 * * *'
  ## Manual request that can be used for testing and retriggering failed updates
  workflow_dispatch:
jobs:
  generate_api_specs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install jq
        run: sudo apt-get install jq
      - name: Fetch OpenAPI doc
        run: python scripts/fetch_api.py
  start-generate-sdks-workflow:
    needs: generate_api_specs # these 'need' fields are used to keep jobs running in order
    uses: ./.github/workflows/generate-sdks.yaml
    with:
      download_url: ${{ github.event.client_payload.download_url }}
  start-generate-errors-workflow:
    needs: start-generate-sdks-workflow 
    uses: ./.github/workflows/generate-errors.yaml
  make-pull-request:
    needs: start-generate-errors-workflow 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make pull request
        uses: peter-evans/create-pull-request@v4
        with:
            title: "fix(${{ github.event.client_payload.id }}): automated openapi files update"
            commit-message: "fix(${{ github.event.client_payload.id }}): update for ${{ github.event.client_payload.id }} SDK"
            author: "app-services-ci <app-services-ci@users.noreply.github.com>"
            branch: chore/generate-api-clients
            branch-suffix: timestamp
            delete-branch: true
            body: |
              _This pull request was auto-generated from [api-update.yaml](https://github.com/redhat-developer/app-services-sdk-core/blob/main/.github/workflows/api-update.yaml)_

              This PR adds the latest openapi files
