name: JavaScript Release
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version being released as X.Y.Z'
        required: true
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js 16.3.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.3.0
          registry-url: "https://registry.npmjs.org"
      - run: |
          cd app-services-sdk-js
          yarn install
          yarn build
      - name: Inject slug/short variables
        # v4
        uses: rlespinasse/github-slug-action@a362e5fb42057a3a23a62218b050838f1bacca5d
      # - name: Validate Tag
      #   run: |
      #     cd app-services-sdk-js
      #     yarn semver $GITHUB_REF_SLUG
      - name: Update versions of packages
        run: VERSION=${{ github.event.inputs.release-version }} bash scripts/update-js-packages.sh
      - name: Publish packages
        run: |
          cd app-services-sdk-js
          npm publish --workspace=packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} #