name: Release Java Workflow

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version being released'
        required: true
      branch:
        description: 'Branch to release from'
        required: true
        default: 'main'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Compile
        working-directory: ./app-services-sdk-java
        run: |
          mvn clean install -DskipTests
      - name: Set git identity
        run: |
          git config user.name ci-bot
          git config user.email ci-bot@andreatp.io
      - name: Release the new version
        working-directory: ./app-services-sdk-java
        run: |
          mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${{ github.event.inputs.release-version }}
          git add .
          git commit -m "Release version update ${{ github.event.inputs.release-version }}"
          git push
          git tag ${{ github.event.inputs.release-version }}
          git push origin ${{ github.event.inputs.release-version }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release-version }}
      - name: Back to Snapshot
        working-directory: ./app-services-sdk-java
        run: |
          mvn versions:set -DgenerateBackupPoms=false -DnewVersion=999-SNAPSHOT
          git add .
          git commit -m "Snapshot version update"
          git push